### ISSUE TITLE
Return browser support

### ISSUE THREAD

**Issue by ca-d** [noppa/xmllint-wasm#1]
Node.js can already call `libxml2` through native bindings, but I desperately need schema validation in the browser.

`README.md` says

> Currently, the library only works in Node.js, but browser support could be added if there's a demand for it.

How much work do you estimate this would be? Where would you start if you needed this? I would like to start working on a pull request to that effect immediately.

**Comment by ca-d** [comment]
Might reliance on thread workers be mitigated by something like https://threads.js.org/ ?

**Comment by philipsens** [comment]
Is there any progress regarding a browser version for this library?

**Comment by ca-d** [comment]
As I haven't seen any progress since, I've gone ahead and written a much faster C library for *schema validation only* (could be easily adapted to provide other `xmllint` functionality) at https://github.com/openscd/xmlvalidate.js . The ready-to-use compiled version works in a WebWorker, for which a very simple `worker.js` wrapper is supplied as well.

You can find the compiled version in the `dist/` directory there, I'm always happy about feedback. The library doesn't have much documentation yet, so please don't hesitate to open issues for any usage questions.

**Comment by noppa** [comment]
Sorry for the silence, for some reason GitHub didn't notify me about this issue so I didn't notice it until now. I don't think adding browser support would be a big issue, I'll look into it in a few days if there's still a need for it.

Apparently GitHub defaults to inheriting the Watch settings from the forked repo instead of notifying for all activity like for non-forked new repos... :|

**Comment by ca-d** [comment]
> Sorry for the silence [...]

No worries, this is an open source project after all: Thanks for your reply!

> [...] I'll look into it in a few days if there's still a need for it.

I believe there's always going to be a need for performant XML validation in the browser.

However, while [kripken's original](https://github.com/kripken/xml.js/) choice of simply compiling the full `xmllint` command line tool was great for exercising `emscripten`'s POSIX filesystem and terminal emulation, it made the resulting library fairly large, slow and memory hungry (e.g. by copying the XML strings into `int32` arrays). It also meant the loss of features like UTF-8 support and a poor API which pukes all errors at the user at the end of the validation process in one big pile. This forbids validating much international XML and is unacceptable in terms of run time (blocking the main browser thread) as well as in terms of memory demands for validating large XML files (one real-life example 90MB XML file was enough for us to exceed V8's memory bounds in Google Chrome running on a 32GB RAM workstation).

To correct for these issues, we've implemented the library [xmlvalidate.js](https://github.com/openscd/xmlvalidate.js) based on `libxml2`, which currently does W3C schema validation only and works in WebWorkers in the browser (our intended use case), but can very easily be adapted to the Node.js target and other validation tasks. If you are interested in these performance and usability improvements as well, feel free to open an issue describing your own Node.js use case, and we'll be happy to accommodate it if possible.

Either way, thank you for publishing this project under a free license. ❤️

**Comment by noppa** [comment]
@c-dinkel My use case for the lib is to run it in AWS Lambda, where installing native dependencies is not very fun. We have also faced some memory limit issues with the current solution so I'll def look into using your solution in a couple of weeks.

**Comment by fhaftmann** [comment]
I want to revive this thread.

I am interested in a browser-enabled version of xmlllint-wasm and as a case study I did the following fork: https://github.com/fhaftmann/xmllint-wasm/tree/browser.

My idea to reconcile would be to provide different entrance points to the library, importing common code from a dedicated module. But I first want to collect feedback before going ahead – maybe there is a simpler solution I did miss so far.

**Comment by noppa** [comment]
Might take a week or so before I have the time to take a proper look at your implementation, but I'll say right now that I'm def open to the idea. The only reason that this isn't implemented yet is that I don't personally have a use-case for it so I haven't spent time on it either.

**Comment by fhaftmann** [comment]
Thanks a lot. Let me emphasize again that this implementation is a fork demonstrating that it is possible, but we need discussion what a suitable way to integrate it would be.

**Comment by noppa** [comment]
Just a heads up that I now have a branch where I have cherry-picked @fhaftmann 's and @th-we 's commits. Still have to do some work to make things still work for both Node and borwser side by side nicely, but I'm hoping I'll get that done in a few days.

If you two are cool with me merging your work in here, I think we could get this resolved soon.

**Comment by alexturpin** [comment]
Just reviving this thread again 👋  has anyone got anything working in browsers?

**Comment by noppa** [comment]
I actually have the feature merged to master already but didn't get around to publishing yet 😓 I'll do that after the holidays I promise. If you are eager and can handle installing emscripten etc, you can clone the repo and build from source with the instructions in the readme.

**Comment by alexturpin** [comment]
No worries, that's great news, thank you! I'll monitor for a release. Happy holidays!

**Comment by jmfadeley** [comment]
Has browser support been added?

**Comment by noppa** [comment]
I just released version ~3.0.0~ 3.0.1 with browser support. [Readme has a quick how-to](https://areena.yle.fi/1-50206655) for it. 

Should work out of the box in Chrome, Edge and Safari (not in Firefox yet I'm afraid) if you import _./node_modules/xmllint-wasm/index-browser.mjs_ module directly. If you use a bundler (which is also required for Firefox to work), you should be able to just do `import * as xmllint form 'xmllint-wasm'`.

Thanks again @fhaftmann for the initial implementation!

**Comment by noppa** [comment]
Closing, as this is now in the package. Feel free to open a new issue if there's something wrong with the implementation.
