### ISSUE TITLE
XSD Import Error

### ISSUE THREAD

**Issue by ChristopherDrain** [noppa/xmllint-wasm#11]
Hi

When I try using this on an XSD file that contains an <xsd:import> we are always encountering an error.

e.g.
<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>

Gives:
Error: warning: failed to load external entity "xml.xsd"
file_0.xsd:10: element import: Schemas parser warning : Element 'import': Failed to locate a schema at location 'xml.xsd'. Skipping the import.

Do you know a fix for this?

Package:
![image](https://user-images.githubusercontent.com/101180836/221910921-3d4ef007-9b22-4fa7-9af3-111a0fc8853e.png)

XSD:
![image](https://user-images.githubusercontent.com/101180836/221911066-be584431-a78f-4fcf-b2f4-32ac79370c4f.png)

We have tried things like
1) Changing namespace to https
2) Adding an absolute link in the schemaLocation
3) Changing the namespace references. 

However all return the same error.

**Comment by noppa** [comment]
The tool won't make any HTTP-requests to get the file, you have to load it yourself in your JavaScript code and then provide that in the `schema` array.

```javascript
const xmlXsd = {
  fileName: 'xml.xsd',
  contents: await fs.promises.readFile(pathToXmlXsd, 'utf8'),
}

const validationResult = await validateXML({
  xml: [{
    fileName: 'my-xml-file.xml',
    contents: myXMLFile,
  }],
  schema: [mainXsd, xmlXsd]
})
```

**Comment by ChristopherDrain** [comment]
Hi @noppa 
Thank you so much for your quick response. 

This was indeed the solution to our issue.
However for the schema array we had to pass the mainXsd as the last entry in the array.
schema: [ xmlXsd, mainXsd]

Other than that it works perfectly
