### ISSUE TITLE
Validation required preload [Documentation issue?]

### ISSUE THREAD

**Issue by flipswitchingmonkey** [noppa/xmllint-wasm#12]
Hi, first of all thanks for the package 👍 

I've set up a validation function for SAML requests and had to add prefetch to the options, which the documentation does not mention. Either I did something conceptually wrong or maybe it would be a good thing to mention in the docs.

Here's what I did (abbreviated):

```ts
//... loading all schemas as const strings from ts files
const xmlProtocol: XMLFileInfo = {
	fileName: 'saml-schema-protocol-2.0.xsd',
	contents: xsdSamlSchemaProtocol20,
};

//...

export async function validateResponse(response: string): Promise<boolean> {
	try {
		const validationResult = await validateXML({
			xml: [
				{
					fileName: 'response.xml',
					contents: response,
				},
			],
			extension: 'schema',
			schema: [xmlProtocol],
			preload: [xmlMetadata, xmlAssertion, xmldsigCore, xmlXenc, xml],
		});
		if (validationResult.valid) {
			return true;
		} 
	} catch (error) {
                console.log(error);
	}
	return false;
}
```
Just loading all the XSD as a `schema` array did not work, the dependencies never resolved. I had to load the primary XSD as `schema`, and all dependencies as `preload`. That works.

**Comment by noppa** [comment]
Yeah that's the intended use for `preload`. We should definitely add a mention of that to README. I also just now noticed that the link to type definitions is also broken :facepalm:

**Comment by noppa** [comment]
The `preload` option is now mentioned in the README example. Thanks for raising the issue
