### ISSUE TITLE
TS1036 error for v4

### ISSUE THREAD

**Issue by igeorgiev-ewave** [noppa/xmllint-wasm#16]
I get a `TS1036: Statements are not allowed in ambient contexts.` error when importing from the package and compiling with `tsc`.

**Steps to reproduce:**
1. Open https://stackblitz.com/edit/node-npm-run-script-bbegdr?file=package.json
2. Wait for `npm install` to complete
3. Run `npm run build`
4. Observe the error

```
> typescript@0.0.0 build
> tsc

node_modules/xmllint-wasm/index-node.d.ts:6:2 - error TS1036: Statements are not allowed in ambient contexts.

6 };
   ~


Found 1 error in node_modules/xmllint-wasm/index-node.d.ts:6
```

I'm able to reproduce the error locally as well, but I shared the Stackblitz link because it's easier to share and reproduce.

**Comment by noppa** [comment]
Thanks for the report, my bad for accidentally not actually testing the library definition files correctly even though I had TypeScript validation set up in CI and all :facepalm:

Fixed in 4.0.1.
