### ISSUE TITLE
Update README.md, Validation against multiple XSD Works !

### ISSUE THREAD

**Issue by sdykae** [noppa/xmllint-wasm#2]
as well as `kripken/xml.js` this for with typescript support and promise based response, executes validation against multiple XSD 
![image](https://user-images.githubusercontent.com/50224521/122163826-6bafae80-ce3b-11eb-92fb-47cc0b340f7d.png)

Thank you
![image](https://user-images.githubusercontent.com/50224521/122163851-75391680-ce3b-11eb-9dfa-ba8038aa82c6.png)

Hope browser support someday but this library rocks.

**Comment by sdykae** [comment]
the main XSD file should be the first in the array.

**Comment by noppa** [comment]
I have updated the readme with an example that uses an array in the schema option. I hope that makes it clearer.
